// Generated by `bun init`

/** Set by `build.ts` define so GitHub Pages base is inlined (optional chaining on import.meta breaks this). */
declare const __PUBLIC_BASE_FRONTEND_URL__: string | undefined;

interface ImportMetaEnv {
  readonly BASE_FRONTEND_URL?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
