import path from "path";

/** Pathname prefix for GitHub Pages project sites, e.g. `/repo`. No trailing slash. */
function withPathPrefix(pathPrefix: string, pathname: string): string {
  const p = pathPrefix.replace(/\/$/, "");
  if (!p) return pathname;
  if (pathname === "/") return `${p}/`;
  return `${p}${pathname.startsWith("/") ? pathname : `/${pathname}`}`;
}

/** URLs are pathnames starting with `/`, same origin. */
export async function buildPrecacheUrls(
  distDir: string,
  dataUrls: string[],
  pathPrefix = "",
): Promise<string[]> {
  const htmlPath = path.join(distDir, "index.html");
  const htmlFile = Bun.file(htmlPath);
  if (!(await htmlFile.exists())) {
    throw new Error(`Missing ${htmlPath}; run bundler first.`);
  }
  const html = await htmlFile.text();
  const staticPaths = ["/", "/index.html", "/manifest.webmanifest", "/icon.svg", ...dataUrls];
  const urls = new Set<string>(staticPaths.map(u => withPathPrefix(pathPrefix, u)));

  for (const m of html.matchAll(/(?:href|src)="([^"]+)"/g)) {
    const href = m[1] ?? "";
    if (!href || href.startsWith("data:")) continue;
    if (href.startsWith("./")) {
      const rel = href.slice(2);
      if (rel) urls.add(withPathPrefix(pathPrefix, "/" + rel));
    } else if (href.startsWith("/")) {
      urls.add(href);
    }
  }

  const logo = path.join(distDir, "logo.svg");
  if (await Bun.file(logo).exists()) {
    urls.add(withPathPrefix(pathPrefix, "/logo.svg"));
  }

  return [...urls];
}

export async function writeServiceWorker(distDir: string, precacheUrls: string[]): Promise<void> {
  const js = `/* generated by build */
const CACHE = "energy-exam-v1";
const PRECACHE = ${JSON.stringify(precacheUrls)};

self.addEventListener("install", event => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then(cache =>
        cache.addAll(PRECACHE.map(u => new URL(u, self.location.origin).href)),
      )
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", event => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(req).then(cached => {
      if (cached) return cached;
      return fetch(req).then(response => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE).then(cache => cache.put(req, copy));
        }
        return response;
      });
    }),
  );
});
`;

  await Bun.write(path.join(distDir, "service-worker.js"), js);
  await Bun.write(path.join(distDir, "precache-manifest.json"), JSON.stringify(precacheUrls, null, 2));
}
